
from typing import Optional, Dict, Any, List
from datetime import datetime

class PriceSource:
    def normalize_symbol(self, raw: str) -> str: ...
    def is_supported_symbol(self, symbol: str) -> bool: ...
    def get_current_price(self, symbol: str) -> Optional[Dict[str, Any]]:
        """返回 {"symbol": str, "price": float, "timestamp": datetime, "market": "spot"|"linear"}"""
    def get_price_at(self, symbol: str, at: datetime, category: str = "spot", use_open: bool = True) -> Optional[float]: ...
    def get_klines_range_chunked(self, symbol: str, interval: str,
                                 start_ms: int, end_ms: int, category: str,
                                 limit_per_call: int = 2000) -> List[List[Any]]: ...
    def choose_interval_for_horizon(self, hours: int) -> str: ...
