"""add tweet_image_url

Revision ID: 1b7e891fc2da
Revises: c03e363fb7da
Create Date: 2026-02-13 17:10:47.638271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7e891fc2da'
down_revision: Union[str, None] = 'c03e363fb7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('tweet_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'tweet_image_url')
    # ### end Alembic commands ###
