"""initial schema

Revision ID: c03e363fb7da
Revises: 
Create Date: 2026-02-06 19:46:33.582495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03e363fb7da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traders_username'), 'traders', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('available', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('pnl_daily', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_user_snapshot_date')
    )
    op.create_index(op.f('ix_balance_snapshots_user_id'), 'balance_snapshots', ['user_id'], unique=False)
    op.create_table('copy_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trader_id', sa.String(length=36), nullable=True),
    sa.Column('size_type', sa.String(length=20), nullable=False),
    sa.Column('size_value', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('margin_mode', sa.String(length=10), nullable=False),
    sa.Column('sl_type', sa.String(length=10), nullable=False),
    sa.Column('sl_value', sa.Float(), nullable=False),
    sa.Column('tp_type', sa.String(length=10), nullable=False),
    sa.Column('tp_value', sa.Float(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trader_id', name='uq_user_copy_setting')
    )
    op.create_index(op.f('ix_copy_settings_user_id'), 'copy_settings', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trader_id', sa.String(length=36), nullable=False),
    sa.Column('is_copy_trading', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trader_id', name='uq_user_trader')
    )
    op.create_index(op.f('ix_follows_trader_id'), 'follows', ['trader_id'], unique=False)
    op.create_index(op.f('ix_follows_user_id'), 'follows', ['user_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trader_id', sa.String(length=36), nullable=False),
    sa.Column('tweet_id', sa.String(length=30), nullable=True),
    sa.Column('tweet_text', sa.Text(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('tp_price', sa.Float(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('retweets', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('tweet_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_index(op.f('ix_signals_trader_id'), 'signals', ['trader_id'], unique=False)
    op.create_table('trader_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trader_id', sa.String(length=36), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_return_pct', sa.Float(), nullable=False),
    sa.Column('total_profit_usd', sa.Float(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('profit_grade', sa.String(length=5), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('copiers_count', sa.Integer(), nullable=False),
    sa.Column('signal_to_noise', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'window', name='uq_trader_window')
    )
    op.create_index(op.f('ix_trader_stats_trader_id'), 'trader_stats', ['trader_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('trader_username', sa.String(length=50), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size_usd', sa.Float(), nullable=False),
    sa.Column('size_qty', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trader_stats_trader_id'), table_name='trader_stats')
    op.drop_table('trader_stats')
    op.drop_index(op.f('ix_signals_trader_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_follows_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_trader_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_copy_settings_user_id'), table_name='copy_settings')
    op.drop_table('copy_settings')
    op.drop_index(op.f('ix_balance_snapshots_user_id'), table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_traders_username'), table_name='traders')
    op.drop_table('traders')
    # ### end Alembic commands ###
